DROP TABLE IF EXISTS "USER";
DROP TABLE IF EXISTS "ROLE";

CREATE TABLE IF NOT EXISTS "USER"(
    ID SERIAL PRIMARY KEY,
    USERNAME TEXT NOT NULL,
    PASSWORD TEXT NOT NULL,
    EMAIL TEXT NOT NULL,
    FIRST_NAME TEXT NOT NULL,
    LAST_NAME TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS "ROLE"(
    ID SERIAL PRIMARY KEY,
    ROLE_NAME varchar(20)
);

INSERT INTO "ROLE" VALUES
                          (0, 'ADMIN'),
                          (1, 'SELLER'),
                          (2, 'BUYER');
