CREATE TABLE IF NOT EXISTS "USER"(
    ID SERIAL PRIMARY KEY,
    USERNAME TEXT NOT NULL,
    PASSWORD TEXT NOT NULL,
    EMAIL TEXT NOT NULL,
    FIRST_NAME TEXT NOT NULL,
    LAST_NAME TEXT DEFAULT ''
)
